services:
  bot-service:
    build: .
    container_name: event-stalker-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/usr/src/app/db
    ports:
      - "4001:4001"
    networks:
      - event-stalker-network

networks:
  event-stalker-network:
    driver: bridge

